package rt

// 由 tools/sdkgen/gen.mjs 从 docs/plugin-system/api/plugin-sdk.d.ts 生成(D514)。
// **不要手改**:改定义源,然后 `pnpm --dir tools/sdkgen gen`。
// 谁在用:sdk_contract_test.go 拿它和运行时真挂上的 __linplayer_sdk 逐名比对。

// SDKSpec 定义源里每个命名空间声明了哪些成员。
var SDKSpec = map[string][]string{
	"app": {"capabilities", "devMode", "formFactor", "getSetting", "locale", "platform", "reducedMotion", "setSetting", "version"},
	"assets": {"readBytes", "readText", "url"},
	"bangumi": {"request"},
	"canvas": {"renderToPng"},
	"cast": {"open"},
	"cookies": {"clear", "get", "set"},
	"crypt": {"aesDecrypt", "aesEncrypt", "base64Decode", "base64Encode", "desDecrypt", "desEncrypt", "gbkDecode", "gbkEncode", "hmac", "md5", "rsaDecrypt", "rsaEncrypt", "sha1", "sha256"},
	"debug": {"logs", "plugins", "requests", "setStorage", "stats", "storage", "surfaces", "uiTree"},
	"desktop": {"setTaskbarBadge", "setTaskbarProgress", "setWindowTitle"},
	"download": {"enqueue"},
	"emby": {"request"},
	"events": {"on"},
	"ext": {"ensure", "status"},
	"files": {"cache", "data", "pick", "save", "saveImage"},
	"html": {"parse", "pd", "pdfa", "pdfh", "xpath"},
	"js": {"bundle", "createContext"},
	"media": {"favorites", "getChildren", "getItem", "getLatest", "history", "search", "setFavorite", "setPlayed", "setProgress"},
	"nav": {"back", "onBack", "push", "replace", "setBadge", "setPageOptions"},
	"oauth": {"authorize", "refresh"},
	"player": {"addSubtitle", "command", "extractFrames", "get", "getSubtitleText", "observe", "openPanel", "play", "playUrl", "screenshot", "set", "setOsdVisible", "state", "tracks", "transcribe"},
	"proxy": {"route", "url"},
	"registry": {"list", "put", "remove", "watch"},
	"secrets": {"get", "remove", "set"},
	"servers": {"current", "list"},
	"settings": {"get", "onChange", "set"},
	"sources": {"add", "list", "remove", "update"},
	"spider": {"compatProxyPort", "load", "supported"},
	"storage": {"get", "keys", "remove", "set"},
	"system": {"clipboard", "openApp", "openUrl", "share"},
	"trakt": {"request"},
	"tvChannels": {"publish"},
	"ui": {"confirm", "notify", "openWindow", "prompt", "select", "toast"},
	"wallpaper": {"set"},
	"webview": {"evaluate", "open", "sniff"},
	"widgets": {"update"},
}

// SDKComponents 定义源里声明的 UI 组件名。SDK 上每个名字挂的就是它自己(字符串),
// 因为 JSX 的 <View> 编译成标识符 View,而 Preact 见到字符串类型就建宿主元素。
var SDKComponents = []string{
	"Badge",
	"Button",
	"Canvas",
	"Checkbox",
	"Chip",
	"ChipGroup",
	"Column",
	"DetailHeader",
	"Divider",
	"EmptyState",
	"EpisodeGrid",
	"FilterPanel",
	"Icon",
	"Image",
	"LineTabs",
	"Markdown",
	"Player",
	"PosterCard",
	"PosterGrid",
	"PosterRow",
	"Pressable",
	"ProgressBar",
	"RatingList",
	"Row",
	"ScrollView",
	"Select",
	"ServerCard",
	"SettingsGroup",
	"SettingsRow",
	"Skeleton",
	"Slider",
	"Spinner",
	"Stack",
	"Switch",
	"Tabs",
	"Text",
	"TextInput",
	"View",
	"VirtualGrid",
	"VirtualList",
	"WebView",
}

// SDKHooks 定义源里声明的 hooks。它们和组件一样挂在 SDK 根上,
// 少一个的表现是插件拿到 undefined,而报错报在插件那边。
var SDKHooks = []string{
	"useCallback",
	"useContext",
	"useEffect",
	"useErrorBoundary",
	"useMemo",
	"usePlayerState",
	"useReducedMotion",
	"useReducer",
	"useRef",
	"useSetting",
	"useState",
	"useStorage",
	"useTheme",
	"useViewport",
}

// SDKStyleKeys 定义源里 Style 接口声明的样式键。最小 DOM 的白名单要和它一致,
// 否则少的那个键连一条 op 都不发,壳再实现也没用。
var SDKStyleKeys = []string{
	"align",
	"animation",
	"aspectRatio",
	"backdropBlur",
	"background",
	"basis",
	"borderColor",
	"borderWidth",
	"bottom",
	"color",
	"direction",
	"fit",
	"fontFamily",
	"fontSize",
	"fontWeight",
	"gap",
	"grow",
	"height",
	"inset",
	"justify",
	"left",
	"letterSpacing",
	"lineHeight",
	"margin",
	"marginBottom",
	"marginLeft",
	"marginRight",
	"marginTop",
	"marginX",
	"marginY",
	"maxHeight",
	"maxLines",
	"maxWidth",
	"minHeight",
	"minWidth",
	"opacity",
	"overflow",
	"padding",
	"paddingBottom",
	"paddingLeft",
	"paddingRight",
	"paddingTop",
	"paddingX",
	"paddingY",
	"position",
	"radius",
	"right",
	"rotate",
	"scale",
	"shadow",
	"shrink",
	"textAlign",
	"tint",
	"top",
	"transition",
	"translateX",
	"translateY",
	"width",
	"wrap",
	"zIndex",
}
